package com.week13.basicNoFuncClasses;

import java.util.ArrayList;

public class DeliveryRequest {

	private ArrayList<ProductRecord> mProductsToDeliver;
	private int mDeliveryID;
	private String mTimestamp; // should be date
	private Coordinates mCoordinates;

	public DeliveryRequest(String deliveryRequest) {
		mProductsToDeliver = new ArrayList<ProductRecord>();
		// sample delivery request:
		// delivery 1 timestamp 41-41 productName1 7 productName2 8
		deliveryRequest = deliveryRequest.replaceAll("\\p{javaSpaceChar}{2,}", " ").trim();
		String[] deliveryRequestArray = deliveryRequest.split(" ");
		mDeliveryID = Integer.parseInt(deliveryRequestArray[1]);
		// double tempTimestamp=Double.parseDouble(supplyRequestArray[2]);
		// mTimestamp=Date.parse(supplyRequestArray[2]);
		String timestamp = deliveryRequestArray[2];
		mTimestamp = timestamp;

		String rawCoordinates=deliveryRequestArray[3];
		String[] coordinatesString=rawCoordinates.split("-");
		mCoordinates=new Coordinates(Integer.parseInt(coordinatesString[0]),Integer.parseInt(coordinatesString[1]));
		for (int i = 4; i < deliveryRequestArray.length; i += 2) {
			String productName = deliveryRequestArray[i];
			double productQuantity = Double.parseDouble(deliveryRequestArray[i + 1]);
	
			double productWeight = 0.0;
			// ????????????????????? products to deliver arrays generated by
			// delivery request will not contain true product weight but 0.0
			// instead
			// double productWeight=Warehouse.getProductWeight(productName);
			// //or warehouseManager
			ProductRecord productRecord = new ProductRecord(productName, productWeight, productQuantity);
			mProductsToDeliver.add(productRecord);

		}
	}

	//public double getDeliveryTotalWeight() {
		//return 0.0; // stub method; check input
		//product weight should be taken from warehouse instances
	//}

	public Coordinates getCoordinates() {
      return mCoordinates;
	}
	
	public ArrayList<ProductRecord> getProductsToDeliver(){
		return mProductsToDeliver;
	}

	public String toString() {
		String deliveryRequest = "ID: " + mDeliveryID + " timestamp: " + mTimestamp + " ";
		for (ProductRecord pr : mProductsToDeliver) {
			deliveryRequest += pr;
		}
		return deliveryRequest;
	}
}
